import { z } from 'zod';
import { ProcessedParticipant, LessonData } from '../types';

/**
 * Person information for instructor and coordinator
 */
export interface PersonInfo {
  name: string;
  email: string;
  phone?: string;
}

/**
 * Course participant with enrollment order
 */
export interface CourseParticipant {
  id: string;
  name: string;
  email: string;
  enrollmentOrder: number;
  isActive: boolean;
  isPermanentAbsent?: boolean; // Always absent for entire course
  aliases?: Array<{
    name: string;
    originalEnrollmentOrder?: number;
  }>;
  mergedFromIds?: string[]; // IDs of participants merged into this one
}

/**
 * Session information for morning/afternoon
 */
export interface SessionInfo {
  startTime: string; // HH:MM format
  endTime: string;   // HH:MM format
  duration: number;  // minutes
}

/**
 * Lesson schedule for a specific date
 */
export interface LessonSchedule {
  date: string; // YYYY-MM-DD
  sessions: {
    morning?: SessionInfo;
    afternoon?: SessionInfo;
  };
  lessonType: 'online' | 'presence' | 'hybrid';
  subject?: string;
}

/**
 * Course settings and configurations
 */
export interface CourseSettings {
  minimumAttendancePercentage: number;
  allowManualAdjustments: boolean;
  autoGenerateDocuments: boolean;
  emailNotifications: boolean;
  backupFrequency: 'daily' | 'weekly' | 'manual';
}

/**
 * Course metadata
 */
export interface CourseMetadata {
  createdAt: string;
  updatedAt: string;
  version: string;
  totalLessons: number;
  completedLessons: number;
}

/**
 * Main course data structure
 */
export interface CourseData {
  courseId: string;
  courseInfo: {
    name: string;
    startDate: string;
    endDate: string;
    instructor: PersonInfo;
    coordinator: PersonInfo;
  };
  participants: CourseParticipant[];
  schedule: LessonSchedule[];
  settings: CourseSettings;
  metadata: CourseMetadata;
}

/**
 * Stored file in IndexedDB
 */
export interface StoredFile {
  filename: string;
  data: ArrayBuffer;
  uploadedAt: string;
  size: number;
}

/**
 * Manual adjustment for participant hours
 */
export interface ManualAdjustment {
  participantId: string;
  session: 'morning' | 'afternoon';
  originalHours: number;
  adjustedHours: number;
  reason: string;
  adjustedBy: string;
  adjustedAt: string;
}

/**
 * Generated documents for a lesson
 */
export interface GeneratedDocuments {
  moduloB?: {
    filename: string;
    data: ArrayBuffer;
    generatedAt: string;
  };
  absenceReport?: {
    filename: string;
    data: ArrayBuffer;
    generatedAt: string;
  };
}

/**
 * Processed lesson data for course context
 */
export interface ProcessedLessonData extends LessonData {
  courseId: string;
  dayNumber: number;
  isProcessed: boolean;
  hasManualAdjustments: boolean;
}

/**
 * Daily lesson data stored in IndexedDB
 */
export interface DailyLessonData {
  courseId: string;
  date: string;
  csvFiles: {
    morning?: StoredFile;
    afternoon?: StoredFile;
  };
  processedData?: ProcessedLessonData;
  manualAdjustments: ManualAdjustment[];
  documents: GeneratedDocuments;
  status: 'pending' | 'processing' | 'completed' | 'error';
}

/**
 * Course participant extended with course-specific data
 */
export interface CourseProcessedParticipant extends ProcessedParticipant {
  courseId: string;
  totalCourseHours: number;
  attendanceDays: string[];
  absenceDays: string[];
  manualAdjustments: ManualAdjustment[];
}

/**
 * Attendance report data
 */
export interface AttendanceReport {
  courseId: string;
  generatedAt: string;
  totalParticipants: number;
  totalLessons: number;
  averageAttendance: number;
  participantSummaries: ParticipantSummary[];
}

/**
 * Individual participant summary
 */
export interface ParticipantSummary {
  participantId: string;
  name: string;
  email: string;
  totalHours: number;
  attendedLessons: number;
  missedLessons: number;
  attendancePercentage: number;
  lastAttendance?: string;
}

// Zod Schemas for validation
export const PersonInfoSchema = z.object({
  name: z.string().min(1, 'Nome richiesto'),
  email: z.string().email('Email non valida'),
  phone: z.string().optional(),
});

export const CourseParticipantSchema = z.object({
  id: z.string(),
  name: z.string().min(1, 'Nome richiesto'),
  email: z.string().email('Email non valida'),
  enrollmentOrder: z.number().min(1),
  isActive: z.boolean(),
  isPermanentAbsent: z.boolean().optional(),
  aliases: z.array(z.object({
    name: z.string(),
    originalEnrollmentOrder: z.number().optional(),
  })).optional(),
  mergedFromIds: z.array(z.string()).optional(),
});

export const SessionInfoSchema = z.object({
  startTime: z.string().regex(/^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/, 'Formato orario non valido (HH:MM)'),
  endTime: z.string().regex(/^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/, 'Formato orario non valido (HH:MM)'),
  duration: z.number().min(1),
});

export const LessonScheduleSchema = z.object({
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Formato data non valido (YYYY-MM-DD)'),
  sessions: z.object({
    morning: SessionInfoSchema.optional(),
    afternoon: SessionInfoSchema.optional(),
  }),
  lessonType: z.string(),
  subject: z.string().optional(),
});

export const CourseSettingsSchema = z.object({
  minimumAttendancePercentage: z.number().min(0).max(100),
  allowManualAdjustments: z.boolean(),
  autoGenerateDocuments: z.boolean(),
  emailNotifications: z.boolean(),
  backupFrequency: z.string(),
});

export const CourseDataSchema = z.object({
  courseId: z.string(),
  courseInfo: z.object({
    name: z.string().min(1, 'Nome corso richiesto'),
    startDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Formato data non valido'),
    endDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Formato data non valido'),
    instructor: PersonInfoSchema,
    coordinator: PersonInfoSchema,
  }),
  participants: z.array(CourseParticipantSchema),
  schedule: z.array(LessonScheduleSchema),
  settings: CourseSettingsSchema,
  metadata: z.object({
    createdAt: z.string(),
    updatedAt: z.string(),
    version: z.string(),
    totalLessons: z.number(),
    completedLessons: z.number(),
  }),
});

export const ManualAdjustmentSchema = z.object({
  participantId: z.string(),
  session: z.string(),
  originalHours: z.number(),
  adjustedHours: z.number(),
  reason: z.string().min(1, 'Motivo richiesto'),
  adjustedBy: z.string(),
  adjustedAt: z.string(),
});

export const DailyLessonDataSchema = z.object({
  courseId: z.string(),
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  csvFiles: z.object({
    morning: z.object({
      filename: z.string(),
      data: z.instanceof(ArrayBuffer),
      uploadedAt: z.string(),
      size: z.number(),
    }).optional(),
    afternoon: z.object({
      filename: z.string(),
      data: z.instanceof(ArrayBuffer),
      uploadedAt: z.string(),
      size: z.number(),
    }).optional(),
  }),
  processedData: z.any().optional(), // ProcessedLessonData
  manualAdjustments: z.array(ManualAdjustmentSchema),
  documents: z.object({
    moduloB: z.object({
      filename: z.string(),
      data: z.instanceof(ArrayBuffer),
      generatedAt: z.string(),
    }).optional(),
    absenceReport: z.object({
      filename: z.string(),
      data: z.instanceof(ArrayBuffer),
      generatedAt: z.string(),
    }).optional(),
  }),
  status: z.string(),
});
